name: CDR API - Local
values:
  - key: base_url
    value: ''
  - key: job_id
    value: ''
  - key: forecast_json
    value: ''
  - key: schedule_json
    value: ''
  - key: output_year
    value: ''
  - key: leave_agent_id
    value: ''
  - key: leave_date
    value: ''
  - key: agent_1
    value: ''
  - key: agent_2
    value: ''
  - key: swap_date
    value: ''
